import "@/styles/globals.css";
import type { AppProps } from "next/app";
import Head from "next/head";
import ButtonAppBar from "@/components/sidebar";
import { ThemeProvider } from "@mui/material";
import theme from "@/components/theme";

export default function App({ Component, pageProps }: AppProps) {
  return (
    <>
      <Head>
        <title>Nerede Kal Case</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logoo.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="" />
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/css2?family=Roboto:wght@300;400;500;700&display=swap"
        />
      </Head>
      <>
        <ThemeProvider theme={theme}>
          <ButtonAppBar />
          <Component {...pageProps} />
        </ThemeProvider>
      </>
    </>
  );
}
