import Head from "next/head";
import UserService from "../../services/user-service";
import { useEffect, useState } from "react";

export default function Home() {
  const [data, setData] = useState([]);
  const getUserList = async () => {
    const response = await UserService.GetAll();
    if(response.status === 200){
      setData(response.data)
    }
}
useEffect(()=>{
  getUserList()
},[])

console.log(data);
  return (
    <>
      <Head>
        <title>Nerede Kal Case</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logoo.ico" />
      </Head>
      
      
    </>
  );
}
